# Generated by Django 4.0.4 on 2022-04-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='clockintime',
            new_name='clockIn',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='clockouttime',
            new_name='clockOut',
        ),
    ]
