# Generated by Django 4.0.4 on 2022-04-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_clockintime_timesheet_clockin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='clockIn',
            new_name='clockedIn',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='clockOut',
            new_name='clockedOut',
        ),
    ]
