# Generated by Django 4.0.4 on 2022-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_clockin_timesheet_clockedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
